all: step1 step2 step3

step1: step1.c 
	gcc -o step1 --std=gnu99 -Wall -Werror -pedantic step1.c

step2: step2.c
	gcc -o step2 --std=gnu99 -Wall -Werror -pedantic step2.c

step3: step3.c
	gcc -o step3 --std=gnu99 -Wall -Werror -pedantic step3.c
